export default [
  { byteToRead: 0, encoding: "s32", property: "isRaceOn" },
  { byteToRead: 4, encoding: "u32", property: "timestampMS" },
  { byteToRead: 8, encoding: "f32", property: "engineMaxRpm" },
  { byteToRead: 12, encoding: "f32", property: "engineIdleRpm" },
  { byteToRead: 16, encoding: "f32", property: "currentEngineRpm" },
  { byteToRead: 20, encoding: "f32", property: "accelerationX" },
  { byteToRead: 24, encoding: "f32", property: "accelerationY" },
  { byteToRead: 28, encoding: "f32", property: "accelerationZ" },
  { byteToRead: 32, encoding: "f32", property: "velocityX" },
  { byteToRead: 36, encoding: "f32", property: "velocityY" },
  { byteToRead: 40, encoding: "f32", property: "velocityZ" },
  { byteToRead: 44, encoding: "f32", property: "angularVelocityX" },
  { byteToRead: 48, encoding: "f32", property: "angularVelocityY" },
  { byteToRead: 52, encoding: "f32", property: "angularVelocityZ" },
  { byteToRead: 56, encoding: "f32", property: "yaw" },
  { byteToRead: 60, encoding: "f32", property: "pitch" },
  { byteToRead: 64, encoding: "f32", property: "roll" },
  {
    byteToRead: 68,
    encoding: "f32",
    property: "normalizedSuspensionTravelFrontLeft",
  },
  {
    byteToRead: 72,
    encoding: "f32",
    property: "normalizedSuspensionTravelFrontRight",
  },
  {
    byteToRead: 76,
    encoding: "f32",
    property: "normalizedSuspensionTravelRearLeft",
  },
  {
    byteToRead: 80,
    encoding: "f32",
    property: "normalizedSuspensionTravelRearRight",
  },
  { byteToRead: 84, encoding: "f32", property: "tireSlipRatioFrontLeft" },
  { byteToRead: 88, encoding: "f32", property: "tireSlipRatioFrontRight" },
  { byteToRead: 92, encoding: "f32", property: "tireSlipRatioRearLeft" },
  { byteToRead: 96, encoding: "f32", property: "tireSlipRatioRearRight" },
  { byteToRead: 100, encoding: "f32", property: "wheelRotationSpeedFrontLeft" },
  {
    byteToRead: 104,
    encoding: "f32",
    property: "wheelRotationSpeedFrontRight",
  },
  { byteToRead: 108, encoding: "f32", property: "wheelRotationSpeedRearLeft" },
  { byteToRead: 112, encoding: "f32", property: "wheelRotationSpeedRearRight" },
  { byteToRead: 116, encoding: "s32", property: "wheelOnRumbleStripFrontLeft" },
  {
    byteToRead: 120,
    encoding: "s32",
    property: "wheelOnRumbleStripFrontRight",
  },
  { byteToRead: 124, encoding: "s32", property: "wheelOnRumbleStripRearLeft" },
  { byteToRead: 128, encoding: "s32", property: "wheelOnRumbleStripRearRight" },
  { byteToRead: 132, encoding: "f32", property: "wheelInPuddleDepthFrontLeft" },
  {
    byteToRead: 136,
    encoding: "f32",
    property: "wheelInPuddleDepthFrontRight",
  },
  { byteToRead: 140, encoding: "f32", property: "wheelInPuddleDepthRearLeft" },
  { byteToRead: 144, encoding: "f32", property: "wheelInPuddleDepthRearRight" },
  { byteToRead: 148, encoding: "f32", property: "surfaceRumbleFrontLeft" },
  { byteToRead: 152, encoding: "f32", property: "surfaceRumbleFrontRight" },
  { byteToRead: 156, encoding: "f32", property: "surfaceRumbleRearLeft" },
  { byteToRead: 160, encoding: "f32", property: "surfaceRumbleRearRight" },
  { byteToRead: 164, encoding: "f32", property: "tireSlipAngleFrontLeft" },
  { byteToRead: 168, encoding: "f32", property: "tireSlipAngleFrontRight" },
  { byteToRead: 172, encoding: "f32", property: "tireSlipAngleRearLeft" },
  { byteToRead: 176, encoding: "f32", property: "tireSlipAngleRearRight" },
  { byteToRead: 180, encoding: "f32", property: "tireCombinedSlipFrontLeft" },
  { byteToRead: 184, encoding: "f32", property: "tireCombinedSlipFrontRight" },
  { byteToRead: 188, encoding: "f32", property: "tireCombinedSlipRearLeft" },
  { byteToRead: 192, encoding: "f32", property: "tireCombinedSlipRearRight" },
  {
    byteToRead: 196,
    encoding: "f32",
    property: "suspensionTravelMetersFrontLeft",
  },
  {
    byteToRead: 200,
    encoding: "f32",
    property: "suspensionTravelMetersFrontRight",
  },
  {
    byteToRead: 204,
    encoding: "f32",
    property: "suspensionTravelMetersRearLeft",
  },
  {
    byteToRead: 208,
    encoding: "f32",
    property: "suspensionTravelMetersRearRight",
  },
  { byteToRead: 212, encoding: "s32", property: "carOrdinal" },
  { byteToRead: 216, encoding: "s32", property: "carClass" },
  { byteToRead: 220, encoding: "s32", property: "carPerformanceIndex" },
  { byteToRead: 224, encoding: "s32", property: "drivetrainType" },
  { byteToRead: 228, encoding: "s32", property: "numCylinders" },
  { byteToRead: 232, encoding: "f32", property: "positionX" },
  { byteToRead: 236, encoding: "f32", property: "positionY" },
  { byteToRead: 240, encoding: "f32", property: "positionZ" },
  { byteToRead: 244, encoding: "f32", property: "speed" },
  { byteToRead: 248, encoding: "f32", property: "power" },
  { byteToRead: 252, encoding: "f32", property: "torque" },
  { byteToRead: 256, encoding: "f32", property: "tireTempFrontLeft" },
  { byteToRead: 260, encoding: "f32", property: "tireTempFrontRight" },
  { byteToRead: 264, encoding: "f32", property: "tireTempRearLeft" },
  { byteToRead: 268, encoding: "f32", property: "tireTempRearRight" },
  { byteToRead: 272, encoding: "f32", property: "boost" },
  { byteToRead: 276, encoding: "f32", property: "fuel" },
  { byteToRead: 280, encoding: "f32", property: "distanceTraveled" },
  { byteToRead: 284, encoding: "f32", property: "bestLap" },
  { byteToRead: 288, encoding: "f32", property: "lastLap" },
  { byteToRead: 292, encoding: "f32", property: "currentLap" },
  { byteToRead: 296, encoding: "f32", property: "currentRaceTime" },
  { byteToRead: 300, encoding: "u16", property: "lapNumber" },
  { byteToRead: 302, encoding: "u8", property: "racePosition" },
  { byteToRead: 303, encoding: "u8", property: "accel" },
  { byteToRead: 304, encoding: "u8", property: "brake" },
  { byteToRead: 305, encoding: "u8", property: "clutch" },
  { byteToRead: 306, encoding: "u8", property: "handBrake" },
  { byteToRead: 307, encoding: "u8", property: "gear" },
  { byteToRead: 308, encoding: "s8", property: "steer" },
  { byteToRead: 309, encoding: "s8", property: "normalizedDrivingLine" },
] as const;
